version: '2.0'
services:
  api:
    image: msounak/kleur-api:latest
    ports:
      - "8000:8000"
  client:
    image: msounak/kleur-client:latest
    environment:
      - API_URL=api
      - API_PORT=8000
    ports:
      - "80:8501"
    depends_on:
      - api
